### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by 09200515** [09200515/furima-34564#9]
# URL
https://furima-34564.herokuapp.com/

# Basic認証のIDとパスワード
ID: admin
password: 2222

# 出品者用のメールアドレスとパスワード
メールアドレス: a@a
パスワード: aaaaa1

# 購入者用のメールアドレスとパスワード
メールアドレス: aaa@aaa
パスワード: aaaaa2

**Comment by snkw-works** [comment]
@09200515 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン状態の出品者のみ、出品した商品の商品情報を編集できるよう修正しましょう**
現状、「商品の編集ボタン」を押下すると、エラー画面へ遷移してしまいます。
<img width="651" alt="スクリーンショット 2021-02-26 17 19 53" src="https://user-images.githubusercontent.com/54050089/109275433-16359e80-7858-11eb-99f2-d474b157f47a.png">

編集機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

- [ ] **ログイン状態の出品者のみ、出品した商品情報を削除できるよう修正しましょう**
現状、「削除ボタン」を押下すると、エラー画面へ遷移してしまいます。（エラー画面は上記、編集のエラー画面と同様です。）

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by 09200515** [comment]
ご確認ありがとうございます。
条件分岐に記述ミスがありましたので修正いたしました。
改めてご確認よろしくお願いいたします。

**Comment by takumi0530** [comment]
@09200515 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/109286645-dd9cc180-7865-11eb-97a3-fde09baee8df.png)

**Comment by 09200515** [comment]
ご確認いただきありがとうございました！
